### ISSUE TITLE
Supported protocols

### ISSUE THREAD

**Issue by albert-github** [w3c/link-checker#13]
In the version 4.81 (of 2011) the offline usage was possible out of the box. In the current (February 26, 2017 zip) version a message is given about a non supported `file` protocol.  Looking on github it looks like this is due to the change on June 23, 2015 (hash: bdf0e3d) where one of the changes, on line 85 of `checklink`, is:
```
 -   $self->protocols_forbidden([qw(mailto javascript)]);
 +   $self->protocols_allowed([qw(http https ftp)]);
```
the reasoning for this is:   s/forbidden/allowed/ whitelisting easier than blacklisting

Is there a reason for disallowing the `file`  by default? There are, in my opinion, a few solution possibilities:
- patch the `checklink` by adding `file`
- add an option to `checklink` that adds other protocols to the `protocols_allowed`

**Comment by dontcallmedom** [comment]
as far as I can recall, the motivation of disallowing `file:` was to avoid `checklink` users be tricked in revealing the existence of specific files on their computer.

I think allowing the `file` protocol as a command-line option would be a reasonable patch though
