### ISSUE TITLE
W3C validators not getting correct referrer, possibly because of a tilde (~) in url

### ISSUE THREAD

**Issue by jamesrschmidt** [w3c/link-checker#18]
The W3C validators for html and css are no longer recognizing the correct referrer url from my website (they used to). Possibly, this is because there is a tilde (~) in the url. In particular, (http://users.ugent.be/~jaschmid/) shows the validation for (http://users.ugent.be/) with the recommended code `<a href="http://validator.w3.org/check?uri=referer">` (html) and `<a href="http://jigsaw.w3.org/css-validator/check/referer">` (css). I am able to get the correct validation with `<a href="http://validator.w3.org/check?uri=users.ugent.be/~jaschmid/">` and `<a href="http://jigsaw.w3.org/css-validator/validator?uri=users.ugent.be/~jaschmid/">`, however.

**Comment by tripu** [comment]
Filed as issues in respective projects instead (w3c/css-validator#191, w3c/markup-validator#34)
