### ISSUE TITLE
Not recursing across entire website

### ISSUE THREAD

**Issue by darthmall** [w3c/link-checker#19]
I was trying to have the link-checker check an entire site, but after running `checklink -r https://sos.noaa.gov` it reports only having checked 11 documents. I'm sure there are more than 11 pages on the site, am I just not understanding how to use the tool to crawl a site, or misreading the output? I've also tried using the `-D` flag to set a very high depth, but it still only reports checking 11 documents.

If it matters, I'm actually running this with the Docker container, so what the exact command I'm using is

    sudo docker run -it --rm stupchiy/checklink -r https://sos.noaa.gov

Any help would be appreciated.

**Comment by tripu** [comment]
Pinging @tguild, @deniak, @ylafon, who might now something about this.

**Comment by dontcallmedom** [comment]
I can't reproduce this - when I run checklink on the said site, it checks a lot more than 11 documents. Can you maybe paste the output of the checker if that issue is still occurring?
