### ISSUE TITLE
Documentation for link-checker web server missing

### ISSUE THREAD

**Issue by alex4200** [w3c/link-checker#30]
It looks like a documentation for the web server at https://validator.w3.org/checklink is missing. 

What does this tool exactly do?

Does it check links from www.mypage/... to all internal pages www.mypage/... and all outgoing links? Or does it just take depth parameter? 

And what does the 'line' number in the result mean? Just the line of the html of the original document? What about the linked pages like www.mypage/some?

Does it crawl all the subpages of www.mypage? Or not?

**Comment by dontcallmedom** [comment]
thanks - the link to the documentation of the on-line link checker was broken - it is now fixed. I believe https://validator.w3.org/checklink/docs/checklink.html answers the questions you have
