### ISSUE TITLE
incorrect handling of picture source sets

### ISSUE THREAD

**Issue by geekabit-nl** [w3c/link-checker#44]
Consider the following html5 picture tag with source set:

&lt;picture&gt;
   &lt;source srcset='picture-small.jpg 200w, picture-medium.jpg 400w, picture-large.jpg 800w' sizes='100vw'&gt;
   &lt;img src='picture-medium.jpg' alt='a picture frame'&gt;
&lt;/picture&gt;

When this is checked with the link checker, it will look for the non-existing files "200w", "400w" and "800w", which is incorrect behaviour. These values describe image width, not image source. The link checker also checks for the files "picture-small.jpg", "picture-medium.jpg" and "picture-large.jpg", which is correct.

This example is available online at: https://www.geekabit.nl/test/picture-srcset.html

**Comment by dontcallmedom** [comment]
thanks for the clear bug report with an associated test case!
