### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by rrthomas** [w3c/link-checker#49]
The last release (4.81) was in 2011, and there has been considerable development since then. Please could we have a new release? Of course it's possible to simply install from GitHub, but it would be great if a new release made it into distros.

Thanks for link-checker!

**Comment by dontcallmedom** [comment]
I'd be happy to push such a release - would you by any chance be in a position to guide me in terms of how to do so?  I'm afraid I haven't found anybody around that has done a CPAN release, so if you have experience with it, it would be precious

**Comment by rrthomas** [comment]
I have never done this, but I have often wondered! So I looked into it, and it seems to be pretty easy, since the project is already correctly organized (that is the hard part!).

I followed the first [comment](http://blogs.perl.org/users/lady_aleena/2020/10/what-do-i-use-to-release-a-module-to-cpan-for-the-first-time.html#comments) on [this blog post](http://blogs.perl.org/users/lady_aleena/2020/10/what-do-i-use-to-release-a-module-to-cpan-for-the-first-time.html), and on my Ubuntu 20.04 system did the following:

```
$ sudo apt install libcpan-uploader-perl libcss-dom-perl # you might have other missing deps
$ make # this generates some files
$ perl Makefile.PL
$ make test
$ make dist
```

Then at this point I would use `cpan-upload`, according to the blog post comment, but of course I don't have the credentials to do that.

**Comment by dontcallmedom** [comment]
it looks like the package has actually been uploaded under @scop 's profile - @scop would you be amenable to update it to the latest version of the link checker? and/or transition "ownership" of the package?

**Comment by scop** [comment]
I think it would be a good idea to transfer its ownership. It's been a while since I've touched the link checker or done any CPAN releases for anything, so I'd have to re-learn things -- better have someone more actively involved take care of it.

I don't know the mechanics of transferring the ownership, but will try to find something and read up. Meanwhile, if anyone knows where to look offhand, pointers welcome. As well as thoughts/info who'd be the new owner.

**Comment by scop** [comment]
Ok, seems transferring the primary permissions of or adding co-maintainers to a CPAN package is easy, self service at pause.perl.org. Now all I need is the CPAN userid to whom to transfer (or who to make a co-maintainer, maybe do it this way first).

Also, should we do the same for Bundle-W3C-Validator while at it?

**Comment by dontcallmedom** [comment]
@scop - thanks for the reactivity! I've just created a PAUSE account, userid DHM; and +1 on doing it for the W3C Validator Bundle at the same time.

**Comment by scop** [comment]
@dontcallmedom ownership should be transferred over to you now for the two mentioned distributions. I'm still a co-maintainer for a bit in case something's needed, but will bow out when I hear things are working.

**Comment by dontcallmedom** [comment]
https://metacpan.org/dist/W3C-LinkChecker v5.0.0 is out - thank you all for your help!

**Comment by rrthomas** [comment]
Great stuff, thank you!
