### ISSUE TITLE
Incorrect "Some of the links to this resource point to broken URI fragments"

### ISSUE THREAD

**Issue by matkoniecz** [w3c/link-checker#52]
I run https://validator.w3.org/checklink?uri=https%3A%2F%2Fmapsaregreat.com%2Flaser%2F&hide_type=all&depth=&check=Check test and while many links are right now indeed broken, the

> Line: 76 https://github.com/matkoniecz/lunar_assembler
>    Status: 200 OK
>
>    Some of the links to this resource point to broken URI fragments (such as index.html#fragment). 
>    Broken fragments:
>
>        https://github.com/matkoniecz/lunar_assembler#lunar-assembler (line 76)

seems invalid

https://github.com/matkoniecz/lunar_assembler#lunar-assembler seems to be 100% fine

**Comment by dontcallmedom** [comment]
while https://github.com/matkoniecz/lunar_assembler#lunar-assembler indeed works in a javascript-enabled browser, there is no static markup that matches the said anchor, so it cannot be detected by the link checker, and won't work in a non-JavaScript browser

**Comment by matkoniecz** [comment]
Thanks for checking, I was unaware that instead of making proper anchors GitHub only emulates them with JS.

Added adding a proper anchor to my TODO list.
