### ISSUE TITLE
Flag mixed-content in https pages

### ISSUE THREAD

**Issue by davidearl** [w3c/link-checker#7]
Since pretty much all browsers block http embedding in https pages, can I suggest that the W3C link checker could usefully check this condition. (Of course if the source is not via a URL, you'd have to have a check box or some such indicating the source is intended to be served over https, but in the normal case where someone is checking a remote site, you'd already know this). I'm talking about <img src='http://...'>, <video src='http://...'> and related, <iframe src='http://...'> etc.

**Comment by dontcallmedom** [comment]
A note on this (good) idea: it should take into account the [`Upgrade-Insecure-Requests`](https://www.w3.org/TR/upgrade-insecure-requests/)  header when flagging mixed-content embedded resources.
