### ISSUE TITLE
Include instructions for installing with cpanminus and local::lib

### ISSUE THREAD

**Issue by foursixnine** [w3c/link-checker#9]
While it might not be the use case for w3c website, if a user (me in this case) wants to install locally link-checker, a mention to installing through cpanm to install dependencies and local::lib would be great.

i've created a simple (https://github.com/w3c/link-checker/pull/8)[pull request] to the readme with this change.

**Comment by dontcallmedom** [comment]
closed by https://github.com/w3c/link-checker/commit/20c9f55ff2c6d62879631edd3bb0bc28eca5c48c
